### ISSUE TITLE
Current error with api

### ISSUE THREAD

**Issue by ghost** [szymonzaczek/towards-data-science#1]
Hello! Thank you for putting this together.

Should the twitter or python_twitter package be used? I am using twitter now:
twitter                   1.18.0                   pypi_0    pypi

and am experiencing this error currently:
![image](https://user-images.githubusercontent.com/10407878/87469366-2e1e2200-c5e9-11ea-97b7-f252a31f0beb.png)

**Comment by ghost** [comment]
Note that I did change to twitter.api, as Api was not working.

**Comment by ghost** [comment]
Sorry, pip install python-twitter works. My apologies.

**Comment by szymonzaczek** [comment]
Hey Nicholas,

thank you very much for pointing this out - I forgot to mention in the article that I used python-twitter package and that its installation is required for the program to work. This has been corrected though. If you have any more suggestions, please let me know. 

Have a nice day! : )
